name: quizapp
channels:
  - defaults
dependencies:
  - pip=25.0
  - python=3.10.16
  - sqlite=3.45.3
  - pip:
      - checksumdir==1.2.0
      - flask==3.1.0
      - flask-bcrypt==1.0.1
      - flask-sqlalchemy==3.1.1
      - pandas==2.2.3
      - plotly==6.0.0
      - python-dotenv==1.0.1
